#cloud-config
package_upgrade: ${instance_upgrade}
timezone: ${timezone}

write_files:
  - path: "/root/instance.sh"
    permissions: "0700"
    encoding: "gzip+base64"
    content: |
      ${worker_setup_sh_content}

runcmd:
 - bash /root/instance.sh
 - cat /root/cloud-init-output.log > /home/opc/instance.finish

final_message: "The system is finally up, after $UPTIME seconds"
output: {all: '| tee -a /root/cloud-init-output.log'}